import Link from "next/link";
import BrandMark from "@/components/brand-mark";
import { BILLING_TERMS_VERSION, CREATION_PLANS, planPrice, usd } from "@/lib/billing/plans";
import styles from "../../help/page.module.css";
export const metadata = { title: "Subscriptions, pricing & refunds" };
export default function BillingTerms() {
  const sections = [
    ["Before launch", "Makeborne is coming soon. No launch date is promised. Founder checkout is currently being prepared and is not yet accepting payments. When enabled, the founding offer will be a paid prelaunch reservation for your first month or year of access. A verified purchase puts you on the founder waitlist with browsing access; generation and credits remain unavailable until launch. Viewing this page does not reserve a place or start billing. Standard subscriptions open at launch."],
    ["When your subscription starts", "Founders pay the discounted first term at reservation. Recurring billing stays paused while waiting. Your paid access period and first credit allocation begin when Makeborne launches for you, not on the reservation date. Your next payment is due only after that first month or year of access and uses the standard renewal price. The initial charge, automatic renewal, browsing-only prelaunch access and undated launch will be disclosed before payment. For standard subscriptions bought after launch, the access period starts with the purchase."],
    ["Founding and yearly prices", "The founding offer is 30% off the first billing term only: the first month for a monthly subscription or the first year for a yearly subscription. Standard yearly pricing is 20% below twelve standard monthly payments. Together, the first founding year is 44% below twelve standard monthly payments. After the discounted term, your subscription automatically renews at the standard price for the selected plan and interval until you cancel. Prices are in US dollars; applicable tax and any checkout fees are shown by Whop before payment."],
    ["Refund policy", "Except where required by applicable law or Whop's binding policies, subscription payments are non-refundable. We do not offer voluntary refunds for a change of mind, unused credits, or an unused part of a paid term. This policy does not exclude mandatory withdrawal rights, remedies for services that are not supplied or are materially misdescribed, payment-error corrections, or the right to dispute a charge. It does not change the terms of a purchase already made."],
    ["Billing problems and statutory rights", "For billing or access problems, contact kerimsabic69@gmail.com with your purchase reference, or use the support options shown on your Whop receipt. Do not send card details. Any legally required immediate-delivery consent or withdrawal-right acknowledgment must be collected separately at checkout; merely accepting these terms does not waive those rights."],
    ["Credits and annual plans", "Create includes 300 credits, Studio 1,000, and Scale 2,800 per month of access. Annual plans release credits monthly; they do not issue all twelve allocations upfront. Unused included credits expire at the end of their allocation month and do not roll over. Credits are usage allowances, not cash, and cannot be withdrawn or transferred. A credit is not a fixed number of pages, images or slides. Generation estimates show the maximum credits before you approve work. Reserved credits for work that was not delivered are released through usage reconciliation; that is separate from a cash refund."],
    ["Automatic renewal and cancellation", "Monthly subscriptions renew monthly and yearly subscriptions renew yearly, at the standard price shown above after the discounted first term of access. Cancel through your Whop account before the next renewal to stop future charges. Canceling future renewals while waiting preserves your purchased first term at launch unless the payment is refunded or reversed. After launch, cancellation preserves access until the end of the paid term and does not itself request a refund. Any price changes will be disclosed before they apply. We do not promise lifetime founding prices."],
    ["Separate support purchases", "Pay a coffee is a separate US$1 monthly support subscription. It does not include creation access, credits, a founding reservation, or a discount entitlement. The Support the development product is also separate. Neither purchase is required to subscribe to a creation plan."],
  ];
  return <div className={styles.page}><header className={styles.header}><Link href="/" className={styles.brand}><BrandMark size={26} />Makeborne</Link><nav><Link href="/billing">Plans & credits</Link></nav></header><main className={styles.main}><section className={styles.hero}><span className={styles.eyebrow}>CLEAR FROM THE START</span><h1>Your subscription, explained.</h1><p>Pricing, renewal and refund terms · 5 October 2026</p></section><div style={{maxWidth:800,overflowX:"auto"}}><table style={{width:"100%",textAlign:"left",fontSize:14,lineHeight:2.5}}><caption>Standard and first-term founding prices, before tax</caption><thead><tr><th>Plan</th><th>Monthly</th><th>First month</th><th>Yearly</th><th>First year</th></tr></thead><tbody>{CREATION_PLANS.map(p=><tr key={p.id}><th>{p.name}</th><td>{usd(p.monthlyCents)}</td><td>{usd(planPrice(p.id,"monthly",true).priceCents)}</td><td>{usd(planPrice(p.id,"yearly",false).priceCents)}</td><td>{usd(planPrice(p.id,"yearly",true).priceCents)}</td></tr>)}</tbody></table>{sections.map(([title,body])=><section className={styles.question} key={title}><h2 style={{fontSize:20}}>{title}</h2><p style={{fontSize:14,lineHeight:1.8,color:"#6d6676"}}>{body}</p></section>)}<p style={{fontSize:12}}>Terms version: {BILLING_TERMS_VERSION}</p></div></main><footer className={styles.footer}><Link href="/billing">Back to plans</Link><Link href="mailto:kerimsabic69@gmail.com">Billing support</Link></footer></div>;
}
