begin;
do $$
declare
 u uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid(); w uuid:=gen_random_uuid(); p uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); q uuid:=gen_random_uuid(); q2 uuid:=gen_random_uuid(); k uuid:=gen_random_uuid(); r uuid; r2 uuid; s jsonb; t timestamptz:=clock_timestamp();
begin
 insert into auth.users(id,email) values(u,'reserve-'||u||'@example.invalid'),(stranger,'reserve-'||stranger||'@example.invalid');
 insert into public.workspaces(id,name,owner_id) values(w,'Reservation fixture',u);
 insert into public.projects(id,workspace_id,title,kind) values(p,w,'Fixture','website');
 insert into public.artifacts(id,workspace_id,project_id,title,kind) values(a,w,p,'Fixture','website');
 s:=jsonb_build_object('version','generation-proposal-v1','inputHash',repeat('a',64),'approvalHash',repeat('b',64),'input',jsonb_build_object('scope',jsonb_build_object('workspaceId',w,'projectId',p,'artifactId',a),'baseVersionId',null),'workflow',jsonb_build_object('version','workflow-v1','output','website','approved',false,'maximumVendorMicrousd','12','maximumCustomerCredits','3','preparedAt',t,'expiresAt',t+interval '1 hour','stages',jsonb_build_array('{}'::jsonb,'{}'::jsonb,'{}'::jsonb)));
 insert into makeborne_private.generation_proposals(id,workspace_id,project_id,artifact_id,input_hash,approval_hash,snapshot,maximum_vendor_microusd,maximum_customer_credits,prepared_at,expires_at) values(q,w,p,a,repeat('a',64),repeat('b',64),s,12,3,t,t+interval '1 hour');
 insert into makeborne_private.generation_proposals(id,workspace_id,project_id,artifact_id,input_hash,approval_hash,snapshot,maximum_vendor_microusd,maximum_customer_credits,prepared_at,expires_at) values(q2,w,p,a,repeat('a',64),repeat('c',64),jsonb_set(s,'{approvalHash}',to_jsonb(repeat('c',64))),12,3,t,t+interval '1 hour');
 insert into makeborne_private.generation_budgets(workspace_id,vendor_limit,credit_limit) values(w,20,5);
 begin perform makeborne_private.reserve_generation_proposal(q,k,u,repeat('b',64),repeat('a',64)); raise exception 'unexpected spending'; exception when insufficient_privilege then raise notice 'PASS default spending denied'; end;
 update makeborne_private.generation_budgets set spending_enabled=true where workspace_id=w;
 begin perform makeborne_private.reserve_generation_proposal(q,k,stranger,repeat('b',64),repeat('a',64)); raise exception 'unexpected stranger'; exception when insufficient_privilege then raise notice 'PASS nonmember denied'; end;
 insert into public.workspace_members(workspace_id,user_id,role) values(w,stranger,'reviewer');
 begin perform makeborne_private.reserve_generation_proposal(q,k,stranger,repeat('b',64),repeat('a',64)); raise exception 'unexpected reviewer'; exception when insufficient_privilege then raise notice 'PASS reviewer denied'; end;
 begin perform makeborne_private.reserve_generation_proposal(q,k,u,repeat('c',64),repeat('a',64)); raise exception 'unexpected approval'; exception when sqlstate 'PT409' then raise notice 'PASS changed approval denied'; end;
 begin perform makeborne_private.reserve_generation_proposal(q,k,u,repeat('b',64),repeat('d',64)); raise exception 'unexpected input'; exception when sqlstate 'PT409' then raise notice 'PASS changed input denied'; end;
 update makeborne_private.generation_budgets set emergency_stop=true where workspace_id=w;
 begin perform makeborne_private.reserve_generation_proposal(q,k,u,repeat('b',64),repeat('a',64)); raise exception 'unexpected emergency bypass'; exception when insufficient_privilege then raise notice 'PASS emergency stop denied'; end;
 update makeborne_private.generation_budgets set emergency_stop=false where workspace_id=w;
 set local role authenticated;
 begin perform makeborne_private.reserve_generation_proposal(q,k,u,repeat('b',64),repeat('a',64)); raise exception 'unexpected client call'; exception when insufficient_privilege then raise notice 'PASS browser function call denied'; end;
 reset role;
 set local role service_role;
 r:=makeborne_private.reserve_generation_proposal(q,k,u,repeat('b',64),repeat('a',64));
 r2:=makeborne_private.reserve_generation_proposal(q,k,u,repeat('b',64),repeat('a',64));
 if r<>r2 then raise exception 'replay mismatch'; end if;
 raise notice 'PASS service reserve and idempotent replay';
 reset role;
 if not exists(select 1 from makeborne_private.generation_budgets where workspace_id=w and vendor_reserved=12 and credit_reserved=3 and active_reservations=1 and revision=1) then raise exception 'wrong counters'; end if;
 raise notice 'PASS exact counters increment once';
 begin perform makeborne_private.reserve_generation_proposal(q,gen_random_uuid(),u,repeat('b',64),repeat('a',64)); raise exception 'unexpected second reservation'; exception when sqlstate 'PT409' then raise notice 'PASS duplicate proposal denied'; end;
 begin perform makeborne_private.reserve_generation_proposal(q2,k,u,repeat('c',64),repeat('a',64)); raise exception 'unexpected key reuse'; exception when sqlstate 'PT409' then raise notice 'PASS changed request key denied'; end;
 begin perform makeborne_private.reserve_generation_proposal(q2,gen_random_uuid(),u,repeat('c',64),repeat('a',64)); raise exception 'unexpected concurrency'; exception when sqlstate 'MB429' then raise notice 'PASS concurrency bound'; end;
 update makeborne_private.generation_budgets set concurrency_limit=2 where workspace_id=w;
 begin perform makeborne_private.reserve_generation_proposal(q2,gen_random_uuid(),u,repeat('c',64),repeat('a',64)); raise exception 'unexpected overspend'; exception when sqlstate 'MB402' then raise notice 'PASS insufficient budgets denied'; end;
 if (select count(*) from makeborne_private.generation_reservations where workspace_id=w)<>1 then raise exception 'failed operation wrote rows'; end if;
 raise notice 'PASS failed operations leave no allocations';
 update makeborne_private.generation_budgets set vendor_limit=100 where workspace_id=w;
 begin perform makeborne_private.reserve_generation_proposal(q2,gen_random_uuid(),u,repeat('c',64),repeat('a',64)); raise exception 'unexpected credit overspend'; exception when sqlstate 'MB402' then raise notice 'PASS customer credit bound independently enforced'; end;
 update makeborne_private.generation_budgets set vendor_limit=20,credit_limit=100 where workspace_id=w;
 begin perform makeborne_private.reserve_generation_proposal(q2,gen_random_uuid(),u,repeat('c',64),repeat('a',64)); raise exception 'unexpected vendor overspend'; exception when sqlstate 'MB402' then raise notice 'PASS vendor bound independently enforced'; end;
 update makeborne_private.generation_budgets set vendor_limit=100,credit_limit=100 where workspace_id=w;
 update makeborne_private.generation_proposals set prepared_at=t-interval '2 hours', expires_at=t-interval '1 hour',snapshot=jsonb_set(jsonb_set(snapshot,'{workflow,preparedAt}',to_jsonb(t-interval '2 hours')),'{workflow,expiresAt}',to_jsonb(t-interval '1 hour')) where id=q2;
 begin perform makeborne_private.reserve_generation_proposal(q2,gen_random_uuid(),u,repeat('c',64),repeat('a',64)); raise exception 'unexpected expiry'; exception when sqlstate 'PT409' then raise notice 'PASS expired proposal denied'; end;
end $$;
rollback;
