import Link from "next/link";
import BrandMark from "@/components/brand-mark";
import { publicPageMetadata } from "@/lib/site-metadata";
import styles from "../help/page.module.css";
export const metadata = publicPageMetadata("/privacy", "Privacy | Makeborne", "How Makeborne handles account information, project content, and published websites.");
const sections = [
  ["Account information", "When you create an account, Makeborne stores your email address, account identifier, authentication records, and available profile details. Google or GitHub sign-in supplies your provider identifier, email, and basic profile information such as your name and avatar. This information is used to sign you in, associate your projects with your account, and protect access to your workspace. Social sign-in does not request access to your Gmail, Google Drive, or GitHub repositories."],
  ["Projects and client work", "Makeborne processes the prompts, project content, versions, images, client contact details, and notes that you choose to save. Drafts and attachments may be stored locally in your browser; content explicitly saved to your account is stored using Supabase. Only include client information and materials you have permission to use. Workspace permissions determine which members can access account content."],
  ["Public websites", "Publishing makes the selected saved website text and images publicly accessible through its hosting address. Anyone with access to that address, including search engines, may read or copy it. Taking a website offline stops Makeborne from serving the live page, but cannot remove copies already made by visitors or search engines."],
  ["Services that process data", "Supabase provides account authentication, database and file storage. Resend delivers account emails. Vercel hosts the main application, and Cloudflare serves published websites. These services may process request information such as IP addresses, browser information, timestamps and error logs to operate and secure the service. Google and GitHub handle their own sign-in screens and authentication under their privacy policies. Whop processes checkout and subscription management; Makeborne receives account and payment-status information needed to check access. Card entry happens through Whop."],
  ["AI features", "Live AI generation is currently disabled for public use. Selecting a style or attaching a file does not itself mean it has been sent to an AI provider. When external generation becomes available, the service will need to process the submitted brief and selected source material to produce the requested output. Google sign-in information is used for account access, not as source material for model training or generated projects."],
  ["Cookies and browser storage", "Makeborne uses authentication cookies and browser storage for your session, saved briefs, preferences, and recovery of unfinished work. Clearing browser storage may remove drafts and locally stored attachments. Third-party checkout and sign-in pages have their own storage practices."],
  ["Retention and your choices", "Account and project information is kept to provide the service and maintain saved work. Operational logs, backups and billing records can have separate retention requirements. You can edit supported project details, remove local drafts, and take your published websites offline. For an account-data copy, correction or deletion request, contact the address below; identity verification may be needed. You can also revoke Google or GitHub access in that provider’s account settings. Revoking provider access does not automatically delete a Makeborne account or cancel a Whop subscription."],
  ["Contact and updates", "For privacy questions or account-data requests, contact kerimsabic69@gmail.com. This notice describes the current Makeborne preview. It will be updated as the service and its data processing change."],
];
export default function PrivacyPage(){return <div className={styles.page}><header className={styles.header}><Link href="/" className={styles.brand}><BrandMark size={26}/>Makeborne</Link><nav><Link href="/help">Help</Link><Link href="/login">Your account</Link></nav></header><main className={styles.main}><section className={styles.hero}><span className={styles.eyebrow}>YOUR INFORMATION</span><h1>Privacy, explained.</h1><p>Privacy notice · Updated 5 October 2026</p></section><div style={{maxWidth:760}}>{sections.map(([title,body])=><section className={styles.question} key={title}><h2 style={{fontSize:20,letterSpacing:'-.4px'}}>{title}</h2><p style={{fontSize:14,lineHeight:1.8,color:'#6d6676'}}>{body}</p></section>)}</div></main><footer className={styles.footer}><span>© 2026 Makeborne</span><Link href="mailto:kerimsabic69@gmail.com">Privacy contact</Link></footer></div>}
